name: build_dev_image

on:
  push:
#    branches:
#      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ictsc-sachiko
      REGISTRY: ictsc2021.sakuracr.jp
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set tags
        uses: docker/metadata-action@v3
        id: image-tag
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,prefix=dev-,value=latest
            type=sha,prefix=dev-,format=short

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Sakura Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.SAKURACR_USER }}
          password: ${{ secrets.SAKURACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          build-args: |
            app_title=ICTSC DEV リハーサル
            guide_contents=# リハーサル ガイドライン（スコアサーバー）
            app_url=https://contest.dev.ictsc.net
          push: true
          tags: ${{ steps.image-tag.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
