# test
name: build_image

on: [push, pull_request]

jobs:
  build_and_push:
    runs-on: [self-hosted, linux, x64]
    env:
      IMAGE_NAME: ictsc-sachiko
      REGISTRY: ictsc2021.sakuracr.jp
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set tag to environment variable
        id: set-tag
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Sakura Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.SAKURACR_USER }}
          password: ${{ secrets.SAKURACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.version }}
